### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by asdcid** [yatisht/usher#20] opened 2020-11-23 00:54 UTC
Hi,

I tried to install the usher with docker or installUbuntu.sh, but neither of them works. Could you give me some help to install usher?

Part of the error log from docker is:
```
/usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h: Timer expired
 #include <stddef.h>
          ^~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
In file included from /usr/include/c++/7/memory:62:0,
                 from /HOME/usher/oneTBB-2019_U9/./include/tbb/compat/../tbb_stddef.h:452,
                 from /HOME/usher/oneTBB-2019_U9/./include/tbb/compat/condition_variable:70,
                 from /HOME/usher/oneTBB-2019_U9/./src/tbb/condition_variable.cpp:18:
/usr/include/c++/7/bits/stl_algobase.h:60:10: fatal error: /usr/include/c++/7/bits/functexcept.h: Timer expired
 #include <bits/functexcept.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [private_server.o] Error 1
make[1]: *** [tbb_statistics.o] Error 1
make[1]: *** [observer_proxy.o] Error 1
make[1]: *** [condition_variable.o] Error 1
make[1]: *** [spin_rw_mutex_v2.o] Error 1
make[1]: *** [arena.o] Error 1
make[1]: *** [governor.o] Error 1
make[1]: *** [task.o] Error 1
make[1]: *** [tbb_thread.o] Error 1
make[1]: *** [pipeline.o] Error 1
make[1]: *** [concurrent_monitor.o] Error 1
make[1]: *** [semaphore.o] Error 1
make[1]: *** [spin_rw_mutex.o] Error 1
make[1]: *** [reader_writer_lock.o] Error 1
make[1]: *** [scheduler.o] Error 1
make[1]: *** [tbb_misc_ex.o] Error 1
make: *** [tbb] Error 2

CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/HOME/usher/build/CMakeFiles/CMakeOutput.log".
See also "/HOME/usher/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
./installUbuntu.sh: 20: ./installUbuntu.sh: rsync: not found
chmod: cannot access 'faToVcf': No such file or directory
mv: cannot stat 'faToVcf': No such file or directory
The command '/bin/sh -c ./installUbuntu.sh' returned a non-zero code: 1
```

I don't know where it put the log files to, I can't find them in the $HOME folder.

For installUbuntu.sh installation, the error is:
```
rsync: failed to connect to hgdownload.soe.ucsc.edu (128.114.119.163): Connection timed out (110)
```

Cheers,
Raymond

**Comment by yatisht** [comment] 2020-11-23 01:22
Hi Raymond,

I am unable to reproduce your Docker error. Let's try to resolve installUbuntu.sh installation first. Can you try again with the latest version, i.e. after
`git pull`

-Yatish

**Comment by yatisht** [comment] 2020-11-26 04:10
Hi Raymond,

I just wanted to follow up on this. Have you had an opportunity to try this again with the latest version and does it work?

-Yatish

**Comment by asdcid** [comment] 2020-11-26 14:12
Hi Yatisht,

Thanks for reply. 

I downloaded the latest version of Usher, and ran the `installUbuntu.sh`. When I tried to install TBB (make -j), it said:
```
[ 18%] Running cpp protocol buffer compiler on parsimony.proto
[ 18%] Running cpp protocol buffer compiler on parsimony.proto
parsimony.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
CMakeFiles/usher.dir/build.make:81: recipe for target 'parsimony.pb.h' failed
make[2]: *** [parsimony.pb.h] Error 1
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/usher.dir/all' failed
make[1]: *** [CMakeFiles/usher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
parsimony.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
CMakeFiles/matToVcf.dir/build.make:81: recipe for target 'parsimony.pb.h' failed
make[2]: *** [parsimony.pb.h] Error 1
CMakeFiles/Makefile2:123: recipe for target 'CMakeFiles/matToVcf.dir/all' failed
make[1]: *** [CMakeFiles/matToVcf.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
```

It seems that it is related to the version of `proto`? Could you give me some hints to address it? I tried to google this, but I do not quite understand those solutions. 

Cheers,
Raymond

**Comment by yatisht** [comment] 2020-11-27 01:33
Which Ubuntu version are you using? The script supports >= Ubuntu 16.04.

-Yatish

**Comment by asdcid** [comment] 2020-11-27 03:28
Oh, my linux version is `Ubuntu 16.04.6 LTS`. Is it any other method to address this issue? or can I install usher without `sudo`?

Cheers,
Raymond

**Comment by yatisht** [comment] 2020-11-27 03:55
Hmm. Unfortunately, older Ubuntu versions are only supported are via Docker. This is because the required protobuf and cmake versions are not natively supported in the older Ubuntu versions. 

I tried installation on a fresh Ubuntu 16.04 instance on AWS and it worked fine with the following commands:
```
sudo apt install docker.io
sudo docker build --no-cache -t usher .
```
Perhaps try with docker once again?

The other, less desirable, option would be to install protobuf3 using the following instructions: https://gist.github.com/ryujaehun/991f5f1e8c1485dea72646877707f497. It seems that somehow you already have the required cmake version (>=3.8).

-Yatish

**Comment by asdcid** [comment] 2020-11-27 05:30
Hi Yatish,

Finally, I successfully installed it. First, I installed `proto` with `conda`, then changed all proto related paths in `CMakeCache.txt`.

Thanks for your help!
Ray

**Comment by yatisht** [comment] 2020-11-27 06:42
Oh nice. That's great to know.

-Yatish

**Comment by yatisht** [comment] 2021-01-31 06:05
I am closing this issue. Please let me know if you have further issues. Thanks.

-Yatish

**Closed by yatisht** 2021-01-31 06:05 UTC
